# Generated by Django 6.0 on 2026-01-07 23:47

import django.db.models.deletion
import django.utils.timezone
import utils.generate_code
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Student', 'Student'), ('Father', 'Father'), ('Mother', 'Mother')], max_length=20, verbose_name='type')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_images', models.ImageField(blank=True, default='user.png', null=True, upload_to='Images_Profile', verbose_name='Cover Image')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('code', models.CharField(default=utils.generate_code.generate_code, max_length=10)),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('phone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
